apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
      - name: book-app
        image: sumavendrapu/book-app:84dfcba99b4b2013f363c325b829dd7e581536a0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: book-app-config

        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: book-app-secret
              key: DB_PASSWORD

        volumeMounts:
        - name: app-storage
          mountPath: /data

      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: mysql-pvc